# Generated by Django 2.2.5 on 2020-01-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeSpaServer', '0005_auto_20200112_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
